interests = [
    "Cooking",
    "Sports",
    "Music",
    "Travel",
    "Reading",
    "Gaming",
    "Photography",
    "Fitness",
    "Hiking",
    "Art",
    "Writing",
    "Technology",
    "Fashion",
    "Movies",
    "Theater",
    "Science",
    "Dancing",
    "Anime",
    "Volunteering",
    "DIY Projects",
    "Cars",
    "Pets",
    "Coffee Tasting",
    "Baking",
    "Yoga",
    "Investing"
]
